# **Introdução ao XGBoost (*Extreme Gradient Boosting*)**

Historicamente, algoritmos de Machine Learning dos anos 70 e 80 (Regressão Linear, Naive Bayes) lidavam com tipos de dados específicos. Nos anos 90, surgiram opções mais potentes, como Random Forest e o próprio Gradient Boosting, mas que ainda sofriam com *overfitting* e grande perda de velocidade ao lidar com bases de dados gigantes.

O `XGBoost` é veio para mitigar esse problema. Ele é uma biblioteca de aprendizado de máquina focada em algoritmos de gradient boosting baseados em árvores. 

O `XGBoost` é uma implementação avançada e otimizada do *gradient boosting*, que cria modelos fortes combinando vários "aprendizes fracos", onde cada nova árvore corrige os erros da anterior. Utiliza técnicas para processamento paralelo, tornando o treinamento muito rápido. Incorpora regularização (parâmetros L1 e L2) para evitar *overfitting*, resultando em modelos mais generalizáveis.

### **Exemplo Prático Utilizando XGBoost**

#### **Classificação**

In [323]:
# XGBoost:
from xgboost import XGBClassifier

# Dataset:
from sklearn.datasets import load_breast_cancer

# Treino e Teste:
from sklearn.model_selection import train_test_split, cross_val_score

# Normalizador:
from sklearn.preprocessing import StandardScaler

# Metricas de avaliação:
from sklearn.metrics import accuracy_score

In [324]:
# Carregando a base de dados:
data = load_breast_cancer()

X = data.data
y = data.target

print(f'X = {X.shape}')
print(f'y = {y.shape}')

X = (569, 30)
y = (569,)

In [325]:
# Visualizando algumas carcterísticas do dataset:

print(f'Classes: {data.target_names}\n')

print(f'Features: {data.feature_names}\n')

print(f'Quantidade de valores em cada classe: malignant = {list(y).count(0)} | beningn = {list(y).count(1)}')

Classes: ['malignant' 'benign']

Features: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

Quantidade de valores em cada classe: malignant = 212 | beningn = 357

In [326]:
# Dividindo em teste e treino:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

print(f'X_train shape = {X_train.shape}')
print(f'y_train shape = {y_train.shape}')
print(f'X_test shape = {X_test.shape}')
print(f'y_test shape = {y_test.shape}')

X_train shape = (369, 30)
y_train shape = (369,)
X_test shape = (200, 30)
y_test shape = (200,)

In [327]:
# Normalizando os valores:

std_scaler = StandardScaler()

std_scaler.fit(X_train)

X_train = std_scaler.transform(X_train)
X_test = std_scaler.transform(X_test)

In [328]:
# Instânciando o modelo e ajustando:

xgb_classifier = XGBClassifier(n_estimators = 5, max_depth = 5, learning_rate = 0.5, objective='binary:logistic')

scores = cross_val_score(xgb_classifier, X_train, y_train)

for idx, score in enumerate(scores):

    print(f'Score {idx+1}: {score:.2%}')

print(f'Mean = {scores.mean():.2%}')

Score 1: 95.95%
Score 2: 93.24%
Score 3: 97.30%
Score 4: 94.59%
Score 5: 97.26%
Mean = 95.67%

In [329]:
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.5, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=5,
              n_jobs=None, num_parallel_tree=None, ...)

In [330]:
# Avaliando o modelo

predict_test = xgb_classifier.predict(X_test)
acc = accuracy_score(y_test, predict_test)

print(f'acc = {acc:.2%}')

acc = 95.00%

#### **Regressão**

In [331]:
# XGBoost:
from xgboost import XGBRegressor

# Dataset:
from sklearn.datasets import fetch_california_housing

# Treino e Teste:
from sklearn.model_selection import train_test_split

# Normalizador:
from sklearn.preprocessing import StandardScaler

# Metricas de avaliação:
from sklearn.metrics import mean_squared_error, r2_score

In [332]:
# Carregando o dataset:
data = fetch_california_housing()

X = data.data
y = data.target

print(f'X = {X.shape}')
print(f'y = {y.shape}')

X = (20640, 8)
y = (20640,)

In [333]:
# verificando a correlação linear dos dados:

import numpy as np
import pandas as pd

data_df = pd.DataFrame(X)
data_df.columns = [data.feature_names]

data_df[data.target_names[0]] = y

data_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [334]:
data_df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
MedHouseVal,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000

In [335]:
# Dividindo em teste e treino:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

print(f'X_train shape = {X_train.shape}')
print(f'y_train shape = {y_train.shape}')
print(f'X_test shape = {X_test.shape}')
print(f'y_test shape = {y_test.shape}')

X_train shape = (13416, 8)
y_train shape = (13416,)
X_test shape = (7224, 8)
y_test shape = (7224,)

In [336]:
# Normalizando os dados:
std_scaler = StandardScaler()
std_scaler.fit(X_train, y_train)

X_train = std_scaler.transform(X_train)
X_test = std_scaler.transform(X_test)

In [ ]:
# Instânciando o modelo e ajustando:

# Existe uma relação entre n_estimators e learning_rate

xgb_regressor = XGBRegressor(n_estimators = 200, max_depth = 5, learning_rate = 0.35, verbosity = 3)

xgb_regressor.fit(X_train, y_train)

[15:24:14] ======== Monitor (0): HostSketchContainer ========
[15:24:14] AllReduce: 0.005901s, 1 calls @ 5901us

[15:24:14] MakeCuts: 0.009945s, 1 calls @ 9945us

[15:24:14] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (13416, 8, 107328).
[15:24:14] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[15:24:14] ======== Monitor (0): GBTree ========
[15:24:14] BoostNewTrees: 0.233659s, 200 calls @ 233659us

[15:24:14] CommitModel: 6e-05s, 200 calls @ 60us

[15:24:14] ======== Monitor (0): HistUpdater ========
[15:24:14] BuildHistogram: 0.05669s, 800 calls @ 56690us

[15:24:14] EvaluateSplits: 0.049504s, 1000 calls @ 49504us

[15:24:14] InitData: 0.00829s, 200 calls @ 8290us

[15:24:14] InitRoot: 0.03511s, 200 calls @ 35110us

[15:24:14] LeafPartition: 0.021849s, 200 calls @ 21849us

[15:24:14] UpdatePosition: 0.058354s, 1000 calls @ 58354us

[15:24:14] UpdatePredictionCache: 0.004375s, 200 calls @ 4375us

[15:24:14] UpdateTree: 0.228503s, 200 calls @ 228503us

[15:24:14] ======== Monitor (0):  ========
[15:24:14] BuildHist: 0.038402s, 1000 calls @ 38402us

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cpu', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.35, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [338]:
# Analisando 

predict_ = xgb_regressor.predict(X_test)

mse = mean_squared_error(y_test, predict_)

print(f'Root Mean Squared Error: {np.sqrt(mse)}')

[15:24:15] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
Root Mean Squared Error: 0.4711435533767621

In [339]:
r2_score(y_test, predict_)

0.833852507523837